version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # ignore patch updates

  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # ignore patch updates

  - package-ecosystem: "mix"
    directory: "/tests/support/test_server/"
    schedule:
      interval: "daily"

  - package-ecosystem: "swift" 
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # ignore patch updates

  - package-ecosystem: "gradle" 
    directory: "/crates/core/liveview-native-core-jetpack/" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # ignore patch updates

